### ISSUE TITLE
Plugin user confusion

### ISSUE THREAD

**Issue by vip8439** [philicious/koji-scripts-and-plugins#2]
The documentation states:

"# The plugin is run as kojid user so that user needs permissions for signing packages:
# su kojiadmin; koji grant-permission admin kojid"

We do not run any builders on our hub so there is no kojid user on the hub.  Is the plugin meant to be run by the hub or by each builder?  If it is meant to be run by the hub, then what user does the plugin run as when there is no kojid user or can the user be specified?

**Comment by philicious** [comment]
Hm. I havent tested it with a tiered setup. But the signer plugin should be run on the Hub I think. If there is no kojid user on the hbu without a builder what other user is running the plugins? Its probably the same user as the hub is running as. Unfortunately I cant test this now as I dont have a running Koji setup anymore.

**Comment by vip8439** [comment]
You ask a very good question that I have been wondering myself.  I'm having an issue finding that out.  We've never run plugins before in our Koji setup.  I am fairly sure Koji is a WSGI application, so if I find the correct config I could try setting the user it runs as.  As is, I can only guess that Koji itself is running as root or apache.  Alternatively, I could try finding and running a benign plugin that may give me some clue.

**Comment by philicious** [comment]
the plugin is triggered on "postTag". so let it build a target so plugin gets triggered and meanwhile have a `ps afxu` running so you see the user the plugin is run as

**Comment by vip8439** [comment]
I'm leaving my job at the end of the week and I was just trying to use your plugin to make it easier on the other employees by taking out a step (setting up sigul client).  I went ahead and closed the issue because i have to focus on getting them set up for doing Koji builds, signing and syncing to Spacewalk.  If I have time after that, I'll definitely give your suggestion a try.  I definitely appreciate the pointers and, if I do get a chance to look at this further, I'll come back and let you know what worked so we can spread the knowledge!  Thanks again for your help!
